const appConstants = {
  FETCH_BOXES_STARTED: 'FETCH_BOXES_STARTED',
  FETCH_BOXES_COMPLETED: 'FETCH_BOXES_COMPLETED',
  FETCH_BOXES_FAILED: 'FETCH_BOXES_FAILED',
  SAVE_BOX_STARTED: 'SAVE_BOX_STARTED',
  SAVE_BOX_COMPLETED: 'SAVE_BOX_COMPLETED',
  SAVE_BOX_FAILED: 'SAVE_BOX_FAILED'
};

export default appConstants;