const contentConstants = {
  FETCH_BLOG_POSTS_STARTED: 'FETCH_BLOG_POSTS_STARTED',
  FETCH_BLOG_POSTS_COMPLETED: 'FETCH_BLOG_POSTS_COMPLETED',
  FETCH_BLOG_POSTS_FAILED: 'FETCH_BLOG_POSTS_FAILED',
};

export default contentConstants;